/* Generated by tools/amalgamate.sh. Do not edit directly. */
#define URBC_IMPLEMENTATION 1
#include "urbc.h"

#include <stdio.h>
#include <string.h>

static void urbc_cli_print_value(const char *label, Value v)
{
    printf("%s i=%lld u=%llu f=%g p=%p\n",
           label,
           (long long)v.i,
           (unsigned long long)v.u,
           (double)v.f,
           v.p);
}

int main(int argc, char **argv)
{
    UrbcImage image;
    UrbcRuntime rt;
    char err[URBC_ERROR_CAP];
    int dump_stack = 0;
    int argi = 1;
    UHalf i;

    if (argc < 2) {
        fprintf(stderr, "usage: %s [--stack] file.uffi\n", argv[0]);
        return 1;
    }
    if (argi < argc && strcmp(argv[argi], "--stack") == 0) {
        dump_stack = 1;
        argi++;
    }
    if (argi >= argc) {
        fprintf(stderr, "usage: %s [--stack] file.uffi\n", argv[0]);
        return 1;
    }

    urbc_image_init(&image);
    urbc_runtime_init(&rt);

    if (urbc_load_from_file(argv[argi], &image, err, sizeof(err)) != URBC_OK) {
        fprintf(stderr, "load failed: %s\n", err);
        urbc_runtime_destroy(&rt);
        urbc_image_destroy(&image);
        return 1;
    }
    if (urbc_runtime_bind(&rt, &image, NULL, NULL, err, sizeof(err)) != URBC_OK) {
        fprintf(stderr, "bind failed: %s\n", err);
        urbc_runtime_destroy(&rt);
        urbc_image_destroy(&image);
        return 1;
    }
    if (urbc_runtime_run(&rt, err, sizeof(err)) != URBC_OK) {
        fprintf(stderr, "run failed: %s\n", err);
        urbc_runtime_destroy(&rt);
        urbc_image_destroy(&image);
        return 1;
    }

    printf("stack_size=%u\n", (unsigned)rt.stack->size);
    if (rt.stack->size > 0)
        urbc_cli_print_value("top", rt.stack->data[rt.stack->size - 1]);
    if (dump_stack) {
        for (i = 0; i < rt.stack->size; i++) {
            char label[32];
            snprintf(label, sizeof(label), "stack[%u]", (unsigned)i);
            urbc_cli_print_value(label, rt.stack->data[i]);
        }
    }

    urbc_runtime_destroy(&rt);
    urbc_image_destroy(&image);
    return 0;
}
