#!/usr/bin/env python3
from __future__ import annotations

import pathlib
import re
import textwrap

ROOT = pathlib.Path(__file__).resolve().parent.parent
URB_HEADER = ROOT / 'include' / 'urb.h'
PUBLIC_HEADERS = [
    ROOT / 'include' / 'urbc' / 'common.h',
    ROOT / 'include' / 'urbc' / 'ffi_sig.h',
    ROOT / 'include' / 'urbc' / 'format.h',
    ROOT / 'include' / 'urbc' / 'runtime.h',
    ROOT / 'include' / 'urbc' / 'loader.h',
    ROOT / 'include' / 'urbc' / 'api.h',
]
INTERNAL_HEADER = ROOT / 'src' / 'urbc_internal.h'
SOURCES = [
    ROOT / 'src' / 'urbc_format.c',
    ROOT / 'src' / 'urbc_platform.c',
    ROOT / 'src' / 'urbc_ffi_sig.c',
    ROOT / 'src' / 'urbc_loader.c',
    ROOT / 'src' / 'urbc_schema.c',
    ROOT / 'src' / 'urbc_runtime.c',
    ROOT / 'src' / 'urbc_ops_core.c',
    ROOT / 'src' / 'urbc_ops_mem.c',
    ROOT / 'src' / 'urbc_ops_schema.c',
    ROOT / 'src' / 'urbc_ops_ffi.c',
    ROOT / 'src' / 'urbc_api.c',
]

CLI_TEMPLATE = r'''
#include <stdio.h>
#include <string.h>

static void urbc_cli_print_value(const char *label, Value v)
{
    printf("%s i=%lld u=%llu f=%g p=%p\n",
           label,
           (long long)v.i,
           (unsigned long long)v.u,
           (double)v.f,
           v.p);
}

int main(int argc, char **argv)
{
    UrbcImage image;
    UrbcRuntime rt;
    char err[URBC_ERROR_CAP];
    int dump_stack = 0;
    int argi = 1;
    UHalf i;

    if (argc < 2) {
        fprintf(stderr, "usage: %s [--stack] file.dffi\n", argv[0]);
        return 1;
    }
    if (argi < argc && strcmp(argv[argi], "--stack") == 0) {
        dump_stack = 1;
        argi++;
    }
    if (argi >= argc) {
        fprintf(stderr, "usage: %s [--stack] file.dffi\n", argv[0]);
        return 1;
    }

    urbc_image_init(&image);
    urbc_runtime_init(&rt);

    if (urbc_load_from_file(argv[argi], &image, err, sizeof(err)) != URBC_OK) {
        fprintf(stderr, "load failed: %s\n", err);
        urbc_runtime_destroy(&rt);
        urbc_image_destroy(&image);
        return 1;
    }
    if (urbc_runtime_bind(&rt, &image, NULL, NULL, err, sizeof(err)) != URBC_OK) {
        fprintf(stderr, "bind failed: %s\n", err);
        urbc_runtime_destroy(&rt);
        urbc_image_destroy(&image);
        return 1;
    }
    if (urbc_runtime_run(&rt, err, sizeof(err)) != URBC_OK) {
        fprintf(stderr, "run failed: %s\n", err);
        urbc_runtime_destroy(&rt);
        urbc_image_destroy(&image);
        return 1;
    }

    printf("stack_size=%u\n", (unsigned)rt.stack->size);
    if (rt.stack->size > 0)
        urbc_cli_print_value("top", rt.stack->data[rt.stack->size - 1]);
    if (dump_stack) {
        for (i = 0; i < rt.stack->size; i++) {
            char label[32];
            snprintf(label, sizeof(label), "stack[%u]", (unsigned)i);
            urbc_cli_print_value(label, rt.stack->data[i]);
        }
    }

    urbc_runtime_destroy(&rt);
    urbc_image_destroy(&image);
    return 0;
}
'''


def strip_header_guard(text: str) -> str:
    lines = text.splitlines()
    guard_idx = None
    define_idx = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if guard_idx is None and stripped.startswith('#ifndef '):
            guard_idx = i
            continue
        if guard_idx is not None and define_idx is None and stripped.startswith('#define '):
            define_idx = i
            break
        if stripped and not stripped.startswith('//') and not stripped.startswith('/*') and not stripped.startswith('*'):
            break
    if guard_idx is not None and define_idx is not None:
        del lines[guard_idx:define_idx + 1]
    while lines and not lines[-1].strip():
        lines.pop()
    if lines and lines[-1].strip().startswith('#endif'):
        lines.pop()
    out = lines
    return '\n'.join(out).strip() + '\n'


def strip_local_includes(text: str) -> str:
    out = []
    for line in text.splitlines():
        stripped = line.strip()
        if (stripped.startswith('#include "urbc/') or
                stripped == '#include "urbc.h"' or
                stripped == '#include "urbc_internal.h"' or
                stripped == '#include "urb.h"'):
            continue
        out.append(line)
    return '\n'.join(out).strip() + '\n'


def emit_section(title: str, body: str) -> str:
    return f'\n/* ===== {title} ===== */\n\n{body.rstrip()}\n'


def build_urbc_h() -> str:
    parts = [
        '/* Generated by tools/amalgamate.py. Do not edit directly. */',
        '#ifndef URBC_H',
        '#define URBC_H 1',
        '',
    ]
    parts.append(emit_section('include/urb.h', strip_local_includes(strip_header_guard(URB_HEADER.read_text()))))
    for header in PUBLIC_HEADERS:
        body = strip_local_includes(strip_header_guard(header.read_text()))
        parts.append(emit_section(header.relative_to(ROOT).as_posix(), body))
    impl = [
        '#ifdef URBC_IMPLEMENTATION',
        '#ifndef URBC_IMPLEMENTATION_ONCE',
        '#define URBC_IMPLEMENTATION_ONCE 1',
    ]
    internal_body = strip_local_includes(strip_header_guard(INTERNAL_HEADER.read_text()))
    impl.append(emit_section(INTERNAL_HEADER.relative_to(ROOT).as_posix(), internal_body))
    for source in SOURCES:
        body = strip_local_includes(source.read_text())
        impl.append(emit_section(source.relative_to(ROOT).as_posix(), body))
    impl.extend([
        '#endif /* URBC_IMPLEMENTATION_ONCE */',
        '#endif /* URBC_IMPLEMENTATION */',
        '',
        '#endif /* URBC_H */',
        '',
    ])
    parts.append('\n'.join(impl))
    return '\n'.join(parts)


def build_urbccli_c() -> str:
    return textwrap.dedent(
        f'''\
        /* Generated by tools/amalgamate.py. Do not edit directly. */
        #define URBC_IMPLEMENTATION 1
        #include "urbc.h"
        {CLI_TEMPLATE}
        '''
    )


def main() -> None:
    (ROOT / 'urbc.h').write_text(build_urbc_h())
    (ROOT / 'urbccli.c').write_text(build_urbccli_c())
    print('generated urbc.h and urbccli.c')


if __name__ == '__main__':
    main()
